apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruboty
  labels:
    app: ruboty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruboty
  template:
    metadata:
      labels:
        app: ruboty
    spec:
      containers:
        - name: ruboty
          image: asia.gcr.io/kube-test-224908/ruboty:latest
          imagePullPolicy: IfNotPresent
