# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20170310_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puppy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
    ]
