# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-04 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_zenurl_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zenurl',
            name='shortcode',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
