# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-04 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20170304_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='zenurl',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zenurl',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
