# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-07 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20170304_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='zenurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='zenurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
